CREATE TABLE STUDENTS(
    SNUMBER INT NOT NULL PRIMARY KEY,
    SNAME VARCHAR(60) NOT NULL,
    EGN CHAR(10) NOT NULL
);

CREATE TABLE FACULTIES (
  FCODE INT NOT NULL PRIMARY KEY,
  FNAME VARCHAR(255) NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL
);

CREATE TABLE EXAMS (
    ECODE INT UNIQUE NOT NULL,
    ENAME VARCHAR(255) NOT NULL,
    DATE DATE NOT NULL,
    FCODE INT NOT NULL REFERENCES FACULTIES(FCODE),
    PRIMARY KEY(ECODE, ENAME)
);

CREATE TABLE EXAM_REQUESTS (
    SNUMBER INT NOT NULL REFERENCES STUDENTS(SNUMBER),
    ECODE INT NOT NULL REFERENCES EXAMS(ECODE),
    REQUEST_DATE DATE NOT NULL,
    ESESSION INT CHECK(ESESSION > 0),
    PRIMARY KEY(SNUMBER, ECODE)
);

CREATE TABLE STUDENT_EXAMS(
    SNUMBER INT NOT NULL REFERENCES STUDENTS(SNUMBER),
    ECODE INT NOT NULL REFERENCES EXAMS(ECODE),
    GRADE DOUBLE CHECK (GRADE BETWEEN 2.0 AND 6.0),
    PRIMARY KEY(SNUMBER,ECODE)
);