-- READONLY VIEW
CREATE VIEW V_STUDENTS_GRADE
AS
SELECT S.EGN, S.SNAME, E.ENAME, SE.GRADE
FROM STUDENTS S, STUDENT_EXAMS SE, EXAMS E
WHERE S.SNUMBER = SE.SNUMBER AND SE.ECODE = E.ECODE;

-- TEST
SELECT *
FROM V_STUDENTS_GRADE
WHERE GRADE > 4.5
ORDER BY SNAME, GRADE DESC;


-- UPDATABLE
CREATE VIEW V_ALL_STUDENTS_02
AS
SELECT *
FROM STUDENTS
WHERE EGN LIKE '02%';

-- TEST
SELECT * FROM V_ALL_STUDENTS_02;

INSERT INTO V_ALL_STUDENTS_02
VALUES (36, 'Taya Kramer', '0282406351');

UPDATE V_ALL_STUDENTS_02
SET SNAME = 'TAYAAAA KRAMER'
WHERE SNUMBER = 36;

-- CHECK
CREATE VIEW V_ALL_STUDENTS_02_CHECK
AS
SELECT *
FROM STUDENTS
WHERE EGN LIKE '02%'
WITH CHECK OPTION;

-- TEST
INSERT INTO V_ALL_STUDENTS_02_CHECK
VALUES (39, 'Bethany Horn', '0294627463'); -- OK

INSERT INTO V_ALL_STUDENTS_02_CHECK
VALUES (40, 'Jared Davies', '0353720183'); -- NOT OK STARTS WITH 03

SELECT * FROM V_ALL_STUDENTS_02_CHECK;